[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Lura Skye", email = "fuyukai@proton.me"},
]
license = {text = "LGPL-3.0-or-later"}
requires-python = ">=3.12"
dependencies = [
    "scramp>=1.4.5",
    "attrs>=24.2.0",
    "python-dateutil>=2.9.0.post0",
    "anyio>=4.9.0",
    "structlog>=24.4.0",
    "whenever>=0.6.9",
]
name = "pg-purepy"
version = "0.11.1"
description = "A pure-Python anyio-based PostgreSQL adapter."
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Operating System :: OS Independent",
]
readme = "README.rst"

[dependency-groups]
docs = [
    "sphinx>=8.2.3",
    "sphinx-inline-tabs>=2023.4.21",
    "sphinx-autodoc-typehints>=2.5.0",
    "sphinxcontrib-jquery>=4.1",
    "sphinx-rtd-theme>=3.0.1",
]
dev = [
    "trio>=0.27.0",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.2",
    "ujson>=5.10.0",
    "pyright>=1.1.397",
    "pytest>=8.3.3",
]


[tool.pdm.build]
includes = []

[tool.pytest.ini_options]
log_cli_level = "DEBUG"
log_cli = false
addopts = "--cov"

[tool.coverage.run]
branch = true
source = ["pg_purepy"]

[tool.coverage.report]
exclude_lines = [
    "raise UnknownMessageError",  # this only happens if the postgresql server breaks
    "pragma: no cover"  # default behaviour...
]

[tool.ruff]
target-version = "py312"
respect-gitignore = true
# fix = true
src = ["src/pg_purepy"]
line-length = 100
output-format = "full"
preview = true

[tool.ruff.lint]
select = [
  "RUF",
  "F",
  "E",
  "W",
  "I",
  "UP",
  "B",
  "YTT",
  "ASYNC",
  "PYI",
  "SIM",
  "RET",
  "PERF",
]
ignore = [
    "W291",
    "W293",
    "E266"
]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pyright]
pythonVersion = "3.12"
include = ["src"]
typeCheckingMode = "strict"

reportImplicitOverride = "warning"
reportUnusedVariable = false
reportIncompatibleVariableOverride = false
reportPrivateUsage = false
