[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Lura Skye", email = "fuyukaii@proton.me"},
]
license = {text = "LGPL-3.0-or-later"}
requires-python = ">=3.13"
dependencies = [
    "scramp>=1.4.5",
    "attrs>=25.4.0",
    "python-dateutil>=2.9.0.post0",
    "anyio>=4.11.0",
    "whenever>=0.9.3",
]
name = "pg-purepy"
version = "0.12.0"
description = "A pure-Python anyio-based PostgreSQL adapter."
classifiers = [
    "Development Status :: 4 - Beta",
    "Topic :: Database",
    "Topic :: Database :: Front-Ends",
    "Operating System :: OS Independent",
]
readme = "README.rst"

[dependency-groups]
docs = [
    "sphinx>=8.2.3",
    "sphinx-inline-tabs>=2023.4.21",
    "sphinx-autodoc-typehints>=2.5.0",
    "furo>=2025.9.25",
]
dev = [
    "trio>=0.27.0",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.2",
    "ujson>=5.10.0",
    "pytest>=8.4.2",
    "pyrefly>=0.39.1",
    "types-python-dateutil>=2.9.0.20251008",
]


[tool.pytest.ini_options]
log_cli_level = "DEBUG"
log_cli = false
addopts = "--cov"

[tool.coverage.run]
branch = true
source = ["pg_purepy"]

[tool.coverage.report]
exclude_lines = [
    "raise UnknownMessageError",  # this only happens if the postgresql server breaks
    "pragma: no cover"  # default behaviour...
]

[tool.ruff]
target-version = "py313"
respect-gitignore = true
# fix = true
src = ["src/pg_purepy", "tests"]
line-length = 100
output-format = "full"
preview = true

[tool.ruff.lint]
select = [
    "RUF",
    "F",
    "E",
    "W",
    "I",
    "UP",
    "B",
    "Q",
    "YTT",
    "PYI",
    "SIM",
    "RET",
    "PERF",
    "PIE",
    "SIM",
    "C4",
    "FA",
    "ICN",
    "PYI",
    "PT",
    "RET",

    # specific docstring rules
    "D201",
    "D204",
    "D211",
    "D419", # less ugly docstrings
]
ignore = [
    "W291", "W293",
    "RUF036",
    "SIM108",
    "W391",
    "E266",  # Used to delimit things
    # Fucking pyright
    "PIE807"
]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pyrefly]
project-includes = [
    "src",
]
python-version = "3.13.0"
infer-with-first-use = false
