name: CI

on:
    push:
        branches: [mizuki]
    pull_request: {}

jobs:
    verify-types:
        name: "Pyrefly check"
        runs-on: "ubuntu-latest"

        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v5"

            - name: "Install Python 3.12"
              uses: "actions/setup-python@v6"
              with:
                  python-version: "3.14"

            - name: Setup PDM
              uses: pdm-project/setup-pdm@v4
              with:
                cache: true
                cache-dependency-path: pylock.toml

            - name: "Install project"
              run: pdm install --dev

            - name: "Run Pyrefly"
              run: "pdm run pyrefly check"

    test-postgresql:
        strategy:
            fail-fast: false
            matrix:
                postgres-version: ["18", "17", "16", "15", "14"]

        name: "Test on PostgreSQL ${{ matrix.postgres-version }}"
        runs-on: ubuntu-latest

        services:
            postgresql:
                image: "postgres:${{ matrix.postgres-version }}"
                env:
                    POSTGRES_USERNAME: "postgres"
                    POSTGRES_PASSWORD: "postgres"
                    POSTGRES_DB: "postgres"

                ports:
                    - 5432

        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v5"

            - name: "Install Python"
              uses: "actions/setup-python@v6"
              with:
                  python-version: "3.13"

            - name: Setup PDM
              uses: pdm-project/setup-pdm@v4
              with:
                cache: true
                cache-dependency-path: pylock.toml

            - name: "Install project"
              run: pdm install --dev

            - name: "Run Pytest"
              run: "pdm run pytest -rPx --cov --cov-report=json"
              env:
                  POSTGRES_USERNAME: "postgres"
                  POSTGRES_PASSWORD: "postgres"
                  POSTGRES_DATABASE: "postgres"
                  POSTGRES_PORT: "${{ job.services.postgresql.ports[5432] }}"

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              env:
                  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
